"""
Beach trip-hours generation and spatial allocation (NZ, raster-based)

This script produces three output rasters on a common grid:
1) beach_hours_generated.tif
   Annual beach/coast recreation hours generated by each origin cell
   = adult_population * hours_per_adult_per_year(distance_to_coast)

2) beach_hours_experienced.tif
   Annual beach hours experienced at each destination (coastal buffer cells only),
   allocated using a simple gravity-style potential:
       experienced_raw_j = (A_j ** alpha) * sum_i (H_i * exp(-beta * d_ij))
   implemented efficiently using a distance-decay convolution of H_i.

   Then rescaled so:
       sum(experienced) == sum(generated)
   to keep totals consistent.

3) beach_value.tif
   = beach_hours_experienced * VALUE_PER_HOUR_NZD

Important notes / assumptions:
- Beach attractiveness raster is limited to a 1 km coastal buffer; only those cells receive experienced hours and value.
- Allocation is implemented as an unconstrained gravity "potential" using convolution.
  It does NOT compute a per-origin normalised choice probability over all beaches (which is typically too expensive at NZ scale).
  The final rescaling step conserves national total hours.
- All input rasters should ideally be aligned (same CRS, transform, resolution, width/height).
  The script checks alignment and can reproject/resample if you enable RESAMPLE_TO_TEMPLATE.

Dependencies:
- rasterio
- numpy
- scipy (fftconvolve)
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass
from typing import Tuple

import numpy as np
import rasterio

try:
    from scipy.signal import fftconvolve
except ImportError as e:
    raise ImportError("This script requires scipy (scipy.signal.fftconvolve). Install scipy.") from e


# =========================
# Constants (edit these)
# =========================

@dataclass(frozen=True)
class Config:
    # Directories
    from pathlib import Path

    # Directories
    COASTAL_DIR: Path = Path(r"<PROJECT_DIRECTORY>\Cultural\Recreation\Coastal")
    RECREATION_DIR:Path = Path(r"<PROJECT_DIRECTORY>\Cultural\Recreation\Intermediate")
    COMMON_DIR: Path = Path(r"<PROJECT_DIRECTORY>\Common")
    OUTPUT_DIR: Path = COASTAL_DIR

    # Inputs
    ADULT_POP_RASTER: Path = RECREATION_DIR / "pop_adults.tif"
    COAST_PROX_RASTER: Path = COASTAL_DIR / "coastline_all_proximity.tif"
    BEACH_ATTR_RASTER: Path = COASTAL_DIR / "attractiveness_beach.tif"

    # Outputs
    OUT_GENERATED_HOURS: Path = OUTPUT_DIR / "beach_hours_generated.tif"
    OUT_EXPERIENCED_HOURS: Path = OUTPUT_DIR / "beach_hours_experienced.tif"
    OUT_VALUE: Path = OUTPUT_DIR / "value_beach.tif"

    # Generation: hours per adult per year by distance-to-coast (from Water Safety Survey bins)
    # Distances are in kilometres.
    # <10 km, 10–25 km, 26–50, >50 km
    HRS_LT10: float = 101.6
    HRS_10_25: float = 50.8
    HRS_26_50: float = 50.8
    HRS_GT50: float = 18.35

    # Allocation: distance decay and attractiveness strength
    # Allocation weight is proportional to (A ** ALPHA) * exp(-BETA_PER_KM * distance_km)
    ALPHA: float = 2.0
    BETA_PER_KM: float = 0.03

    # Convolution kernel cut-off (max travel distance considered)
    MAX_TRAVEL_KM: float = 250.0

    # Value constant (NZD per hour)
    VALUE_PER_HOUR_NZD: float = 52.0

    # Nodata for outputs
    OUT_NODATA: float = -9999.0

    # Raster alignment behaviour
    # Best practice: pre-align all rasters in GIS. If False, script will error on mismatch.
    RESAMPLE_TO_TEMPLATE: bool = False

    # Logging
    LOG_LEVEL: int = logging.INFO

CFG = Config()

# =========================
# Logging setup
# =========================

logging.basicConfig(
    level=CFG.LOG_LEVEL,
    format="%(asctime)s | %(levelname)s | %(message)s",
)
logger = logging.getLogger("beach_hours_allocation")


# =========================
# Helpers
# =========================

def _check_same_grid(meta_a: dict, meta_b: dict, name_a: str, name_b: str) -> None:
    keys = ["crs", "transform", "width", "height"]
    for k in keys:
        if meta_a.get(k) != meta_b.get(k):
            raise ValueError(
                f"Raster grids do not match: {name_a} vs {name_b} (mismatch in {k}). "
                f"{name_a}.{k}={meta_a.get(k)}; {name_b}.{k}={meta_b.get(k)}"
            )


def hours_per_adult(distance_to_coast_m: np.ndarray) -> np.ndarray:
    """Piecewise hours-per-adult-per-year based on distance to coast bins."""
    d_km = distance_to_coast_m.astype(np.float32) / 1000.0

    out = np.full(d_km.shape, np.nan, dtype=np.float32)
    out[d_km < 10.0] = CFG.HRS_LT10
    out[(d_km >= 10.0) & (d_km <= 25.0)] = CFG.HRS_10_25
    out[(d_km > 25.0) & (d_km <= 50.0)] = CFG.HRS_26_50
    out[d_km > 50.0] = CFG.HRS_GT50

    return out


def build_distance_kernel(
    max_travel_km: float,
    beta_per_km: float,
    pixel_size_x_m: float,
    pixel_size_y_m: float,
) -> np.ndarray:
    """
    Build an isotropic exponential distance-decay kernel:
      K(d) = exp(-beta * d_km) for d_km <= max_travel_km, else 0
    """
    px = abs(pixel_size_x_m)
    py = abs(pixel_size_y_m)

    rx = int(math.ceil((max_travel_km * 1000.0) / px))
    ry = int(math.ceil((max_travel_km * 1000.0) / py))

    y = np.arange(-ry, ry + 1, dtype=np.float32) * py
    x = np.arange(-rx, rx + 1, dtype=np.float32) * px
    xx, yy = np.meshgrid(x, y)
    d_m = np.sqrt(xx * xx + yy * yy)
    d_km = d_m / 1000.0

    kernel = np.exp(-beta_per_km * d_km)
    kernel[d_km > max_travel_km] = 0.0

    s = float(kernel.sum())
    if s <= 0:
        raise ValueError("Kernel sum is zero. Check MAX_TRAVEL_KM and grid resolution.")

    logger.info(
        f"Kernel built: max_travel={max_travel_km} km, beta={beta_per_km}/km, "
        f"shape={kernel.shape}, sum={s:.3f}"
    )
    return kernel.astype(np.float32)


def write_raster(path: str, arr: np.ndarray, template_meta: dict, nodata: float) -> None:
    meta = template_meta.copy()
    meta.update(
        dtype="float32",
        count=1,
        nodata=nodata,
        compress="DEFLATE",
        predictor=2,
        tiled=True,
        bigtiff="IF_SAFER",
    )
    with rasterio.open(path, "w", **meta) as dst:
        dst.write(arr.astype(np.float32), 1)


# =========================
# Main
# =========================

def main() -> None:
    logger.info("Starting beach trip-hours generation and allocation...")

    # Read inputs
    with rasterio.open(CFG.ADULT_POP_RASTER) as pop_ds, \
         rasterio.open(CFG.COAST_PROX_RASTER) as coast_ds, \
         rasterio.open(CFG.BEACH_ATTR_RASTER) as attr_ds:

        if not CFG.RESAMPLE_TO_TEMPLATE:
            _check_same_grid(pop_ds.meta, coast_ds.meta, "adult_population", "coast_proximity")
            _check_same_grid(pop_ds.meta, attr_ds.meta, "adult_population", "beach_attractiveness")

        meta = pop_ds.meta.copy()

        pop = pop_ds.read(1).astype(np.float32)
        coast = coast_ds.read(1).astype(np.float32)
        attr = attr_ds.read(1).astype(np.float32)

        pop_nodata = pop_ds.nodata
        coast_nodata = coast_ds.nodata
        attr_nodata = attr_ds.nodata

    logger.info("Inputs loaded.")

    # Build masks
    pop_valid = np.isfinite(pop)
    coast_valid = np.isfinite(coast)
    attr_valid = np.isfinite(attr)

    if pop_nodata is not None:
        pop_valid &= (pop != pop_nodata)
    if coast_nodata is not None:
        coast_valid &= (coast != coast_nodata)
    if attr_nodata is not None:
        attr_valid &= (attr != attr_nodata)

    # Beach destination mask: where attractiveness exists (your 1 km coastal buffer)
    beach_mask = attr_valid

    # Origin mask: where we can generate hours (need pop and coast distance)
    origin_mask = pop_valid & coast_valid & (pop > 0)

    logger.info(f"Origin cells: {int(origin_mask.sum())} / {origin_mask.size}")
    logger.info(f"Beach destination cells: {int(beach_mask.sum())} / {beach_mask.size}")

    # 1) Generate hours at origin cells
    logger.info("Generating annual beach hours by origin cell (population x distance-to-coast hours)...")
    hpa = hours_per_adult(coast)  # hours per adult per year
    generated = np.zeros(pop.shape, dtype=np.float32)
    generated[origin_mask] = pop[origin_mask] * hpa[origin_mask]

    total_generated = float(np.nansum(generated))
    logger.info(f"Total generated beach hours (national): {total_generated:,.0f}")

    # 2) Allocate to destinations using convolution-based gravity potential
    #    potential_j = sum_i generated_i * exp(-beta * d_ij)
    logger.info("Building distance-decay kernel...")
    pixel_size_x_m = meta["transform"].a
    pixel_size_y_m = meta["transform"].e  # usually negative
    kernel = build_distance_kernel(
        max_travel_km=CFG.MAX_TRAVEL_KM,
        beta_per_km=CFG.BETA_PER_KM,
        pixel_size_x_m=pixel_size_x_m,
        pixel_size_y_m=pixel_size_y_m,
    )

    logger.info("Computing distance-decay potential via convolution (fftconvolve)...")
    # Treat invalid origins as 0 hours for convolution
    origin_hours = np.where(origin_mask, generated, 0.0).astype(np.float32)
    potential = fftconvolve(origin_hours, kernel, mode="same").astype(np.float32)

    # Apply attractiveness
    logger.info("Applying attractiveness weighting at destinations...")
    attr_clamped = np.clip(attr, 0.0, 1.0)
    attr_term = np.zeros_like(attr_clamped, dtype=np.float32)
    attr_term[beach_mask] = np.power(attr_clamped[beach_mask], CFG.ALPHA).astype(np.float32)

    experienced_raw = np.zeros_like(potential, dtype=np.float32)
    experienced_raw[beach_mask] = attr_term[beach_mask] * potential[beach_mask]

    raw_sum = float(np.nansum(experienced_raw))
    logger.info(f"Sum experienced_raw (pre-scaling): {raw_sum:,.0f}")

    if raw_sum <= 0:
        raise RuntimeError("experienced_raw sum is zero. Check attractiveness values, masks, and kernel parameters.")

    # Rescale so total experienced equals total generated
    scale = total_generated / raw_sum
    logger.info(f"Scaling experienced hours by factor: {scale:.6f} to conserve total hours.")

    experienced = np.zeros_like(experienced_raw, dtype=np.float32)
    experienced[beach_mask] = experienced_raw[beach_mask] * scale

    total_experienced = float(np.nansum(experienced))
    logger.info(f"Total experienced beach hours (post-scaling): {total_experienced:,.0f}")

    # 3) Convert to value
    logger.info("Calculating value raster (experienced hours x value per hour)...")
    value = np.zeros_like(experienced, dtype=np.float32)
    value[beach_mask] = experienced[beach_mask] * CFG.VALUE_PER_HOUR_NZD

    # Write outputs
    logger.info("Writing output rasters...")

    # Generated hours raster: keep on full grid (origins), nodata elsewhere
    out_generated = np.full(pop.shape, CFG.OUT_NODATA, dtype=np.float32)
    out_generated[origin_mask] = generated[origin_mask]
    write_raster(CFG.OUT_GENERATED_HOURS, out_generated, meta, CFG.OUT_NODATA)
    logger.info(f"Wrote: {CFG.OUT_GENERATED_HOURS}")

    # Experienced hours raster: only defined for beach_mask cells (1 km buffer), nodata elsewhere
    out_experienced = np.full(pop.shape, CFG.OUT_NODATA, dtype=np.float32)
    out_experienced[beach_mask] = experienced[beach_mask]
    write_raster(CFG.OUT_EXPERIENCED_HOURS, out_experienced, meta, CFG.OUT_NODATA)
    logger.info(f"Wrote: {CFG.OUT_EXPERIENCED_HOURS}")

    # Value raster: only defined for beach_mask cells (1 km buffer), nodata elsewhere
    out_value = np.full(pop.shape, CFG.OUT_NODATA, dtype=np.float32)
    out_value[beach_mask] = value[beach_mask]
    write_raster(CFG.OUT_VALUE, out_value, meta, CFG.OUT_NODATA)
    logger.info(f"Wrote: {CFG.OUT_VALUE}")

    logger.info("Done.")


if __name__ == "__main__":
    main()